import { Category, Condition, Listing, ListingType, ListingStatus } from "./types";

export const MOCK_LISTINGS: Listing[] = [
  {
    id: '1',
    title: 'Casio FX-991EX Calculator',
    description: 'Barely used scientific calculator, essential for Engineering exams. Comes with the original cover.',
    type: ListingType.BUY,
    price: 8500,
    category: Category.ELECTRONICS,
    condition: Condition.LIKE_NEW,
    sellerName: 'David O.',
    contactInfo: '08123456789',
    whatsappNumber: '2348123456789',
    imageUrl: 'https://picsum.photos/seed/calc/400/300',
    createdAt: new Date(),
    status: ListingStatus.AVAILABLE
  },
  {
    id: '2',
    title: 'Medical Lab Coat (Size M)',
    description: 'Standard Unilag medical lab coat. Clean and ironed. Needed for BIO 101 practicals.',
    type: ListingType.RENT,
    rentPrice: 500,
    rentDuration: 'per day',
    category: Category.LAB_GEAR,
    condition: Condition.GOOD,
    sellerName: 'Sarah K.',
    contactInfo: 'sarah.k@student.unilag.edu.ng',
    whatsappNumber: '2349011223344',
    imageUrl: 'https://picsum.photos/seed/coat/400/300',
    createdAt: new Date(),
    status: ListingStatus.AVAILABLE
  },
  {
    id: '3',
    title: 'Samsung A12 -> iPhone X',
    description: 'Want to swap my Samsung A12 (64GB) for an iPhone X. I will add cash on top.',
    type: ListingType.SWAP,
    swapRequest: 'iPhone X or XR',
    category: Category.ELECTRONICS,
    condition: Condition.GOOD,
    sellerName: 'Emmanuel J.',
    contactInfo: '09087654321',
    whatsappNumber: '2349087654321',
    imageUrl: 'https://picsum.photos/seed/phone/400/300',
    createdAt: new Date(),
    status: ListingStatus.AVAILABLE
  },
  {
    id: '4',
    title: 'GST 102 Textbook',
    description: 'Philosophy and Logic textbook. No missing pages. Highlighted key points for easier reading.',
    type: ListingType.BUY,
    price: 1500,
    category: Category.TEXTBOOKS,
    condition: Condition.FAIR,
    sellerName: 'Chidinma',
    contactInfo: '07011223344',
    whatsappNumber: '2347011223344',
    imageUrl: 'https://picsum.photos/seed/book/400/300',
    createdAt: new Date(),
    status: ListingStatus.AVAILABLE
  },
  {
    id: '5',
    title: 'Mini Refrigerator',
    description: 'Moving out of Jaja Hall. Selling my bedside fridge. Cools perfectly.',
    type: ListingType.BUY,
    price: 45000,
    category: Category.HOSTEL,
    condition: Condition.GOOD,
    sellerName: 'Tobi',
    contactInfo: '08099887766',
    whatsappNumber: '2348099887766',
    imageUrl: 'https://picsum.photos/seed/fridge/400/300',
    createdAt: new Date(),
    status: ListingStatus.SOLD
  },
  {
    id: '6',
    title: 'Drafting Board',
    description: 'A3 Drafting board for architecture or engineering students. Need it for just a weekend project?',
    type: ListingType.RENT,
    rentPrice: 1000,
    rentDuration: 'per weekend',
    category: Category.STATIONERY,
    condition: Condition.LIKE_NEW,
    sellerName: 'Ahmed',
    contactInfo: 'ahmed.eng@gmail.com',
    imageUrl: 'https://picsum.photos/seed/board/400/300',
    createdAt: new Date(),
    status: ListingStatus.RENTED
  }
];